### ISSUE TITLE
Make scattertext plot of interesting classes

### ISSUE THREAD

**Issue by hslh** [simondewit/pickleteam#3]
Implementation is here https://github.com/JasonKessler/scattertext. 

Maybe interesting to look at similar classes, like different hearts and unknown classes like the '100'-emoji.

**Comment by Eyokiha** [comment]
I've set up everything to use scattertext on my computer, and I wanted to create some plots. There is a demo.py which I could modify and use. It seems the variables convention_df or corpus should contain our data instead of the example data. The readme only mentions to use a csv file as input for the commandline tool, but not how you can use your own data in a python file. convention_df is of type pandas.core.frame.DataFrame and corpus is of type scattertext.Corpus.Corpus, but I don't know how to turn our pickle file data into one of those.
Any idea how I can use our data in demo.py?

**Comment by hslh** [comment]
It seems like indeed the only way to enter the data is to turn it into a pandas dataframe, and then use CorpusFromPandas on the dataframe to get a scattertext.Corpus.Corpus. [Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html) is a Python library that's often used for data analysis/exploration. I'm not very familiar with it, but it's quite easy to use, and seems very similar to R.  

Anyway, this is the code to read the pickled tweets into a dataframe:
```python
tweets = pickle.load(open(filename, 'rb'))
tweets_df = pd.DataFrame(tweets, columns=['emoji', 'tweet'])
```

To turn it into a scattertext.Corpus.Corpus:
```python
nlp = spacy.en.English()
corpus = st.CorpusFromPandas(tweets_df, category_col='emoji', text_col='tweet', nlp=nlp).build()
```

**Comment by Eyokiha** [comment]
Thanks! It works now.
